import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google';
import './globals.css'
import Footer from '@/components/footer';
import Navbar from '@/components/navbar';
import ModalProvider from '@/providers/modal_provider';
import StoreProvider from '@/store/store_provider';
import ToastProvider from '@/providers/toast_provider';

const font = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={font.className}>
        <StoreProvider>
          <ModalProvider />
          <ToastProvider />
          <Navbar />
          { children }
          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}
